[tool.ruff]
src = ["src"]
[tool.ruff.lint]
ignore = [
    "F722",  # Jaxtype will throw false positives.
    "E731",  # Ignore lambda assignements (why is this even a thing?).
]

[tool.basedpyright]
typeCheckingMode = "basic"
